# Generated by Django 5.2.12 on 2026-03-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("hs_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=2)),
                ("year", models.CharField(max_length=4)),
                ("amount", models.BigIntegerField()),
                ("weight", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("category", "country", "year")},
            },
        ),
        migrations.DeleteModel(
            name="ProductMatch",
        ),
    ]
