# Generated by Django 5.2.12 on 2026-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0002_marketstat_delete_productmatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=10)),
                ("research_month", models.CharField(max_length=7)),
                ("market_size", models.JSONField(blank=True, default=dict)),
                ("kbeauty_share", models.JSONField(blank=True, default=dict)),
                ("trends", models.JSONField(blank=True, default=dict)),
                ("channels", models.JSONField(blank=True, default=dict)),
                ("competitors", models.JSONField(blank=True, default=dict)),
                ("raw_summary", models.TextField(blank=True)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("category", "country", "research_month")},
            },
        ),
    ]
