# Generated by Django 5.2.12 on 2026-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0003_marketresearch"),
    ]

    operations = [
        migrations.CreateModel(
            name="HsClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100, unique=True)),
                ("hs_code", models.CharField(max_length=10)),
                ("reason", models.TextField()),
                ("classified_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
