# Generated by Django 5.2.12 on 2026-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0004_hsclassification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Ulta", "Ulta"),
                            ("Sephora", "Sephora"),
                            ("Qoo10", "Qoo10"),
                            ("Rakuten", "Rakuten"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("US", "US"), ("JP", "JP")], max_length=2
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("platform_item_id", models.CharField(max_length=100)),
                ("title", models.TextField()),
                ("brand", models.CharField(blank=True, default="", max_length=200)),
                ("price", models.CharField(blank=True, default="", max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews_count", models.IntegerField(blank=True, null=True)),
                ("url", models.URLField(max_length=500)),
                ("collected_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["platform", "rank"],
                "unique_together": {("platform", "platform_item_id", "collected_at")},
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=2)),
                ("platform_item_id", models.CharField(db_index=True, max_length=100)),
                ("review_id", models.CharField(max_length=100)),
                ("author", models.CharField(blank=True, default="", max_length=200)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("title_ko", models.TextField(blank=True, default="")),
                ("body_ko", models.TextField(blank=True, default="")),
                ("review_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("platform", "platform_item_id", "review_id")},
            },
        ),
    ]
