# Generated by Django 5.2.12 on 2026-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0005_product_ranking_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="body_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productreview",
            name="body_original",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productreview",
            name="title_original",
            field=models.TextField(blank=True, default=""),
        ),
    ]
