# Generated by Django 5.2.12 on 2026-03-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0006_add_review_multilang"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="productreview",
            name="keybert_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="productreview",
            name="primary_category",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
