# Generated by Django 5.2.12 on 2026-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0007_add_review_category_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAnalysisCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("platform_item_id", models.CharField(max_length=100)),
                ("result", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("platform", "platform_item_id")},
            },
        ),
    ]
