# Generated by Django 5.2.12 on 2026-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0008_add_review_analysis_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaAdSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("ulta", "Ulta"),
                            ("sephora", "Sephora"),
                            ("qoo10", "Qoo10"),
                            ("rakuten", "Rakuten"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(max_length=200)),
                ("total_ads", models.IntegerField(default=0)),
                ("image_ads", models.IntegerField(default=0)),
                ("video_ads", models.IntegerField(default=0)),
                ("image_ratio", models.FloatField(default=0)),
                ("video_ratio", models.FloatField(default=0)),
                ("latest_ad_date", models.DateField(blank=True, null=True)),
                ("recent_30d_ads", models.IntegerField(default=0)),
                ("latest_ad_text", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("channel", "brand")},
            },
        ),
    ]
