# Generated by Django 5.2.12 on 2026-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0009_add_meta_ad_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaadsummary",
            name="page_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
