# Generated by Django 5.2.12 on 2026-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0010_add_page_id_to_meta_ad"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("ulta", "Ulta"),
                            ("sephora", "Sephora"),
                            ("qoo10", "Qoo10"),
                            ("rakuten", "Rakuten"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(db_index=True, max_length=200)),
                ("library_id", models.CharField(blank=True, default="", max_length=50)),
                ("media_type", models.CharField(blank=True, default="", max_length=10)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("ad_text", models.TextField(blank=True, default="")),
                ("page_id", models.CharField(blank=True, default="", max_length=50)),
                ("market", models.CharField(blank=True, default="", max_length=2)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["channel", "brand"],
                        name="market_api__channel_5aeceb_idx",
                    ),
                    models.Index(
                        fields=["market"], name="market_api__market_158726_idx"
                    ),
                ],
                "unique_together": {("channel", "library_id")},
            },
        ),
    ]
