# Generated by Django 5.2.12 on 2026-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0011_add_meta_ad_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="categories_v2",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="productreview",
            name="primary_category_v2",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
